[project]
name = "lms-chat-boat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "langchain>=0.3.26",
    "python-dotenv>=1.1.1",
    "uvicorn>=0.35.0",
]
